### ISSUE TITLE
No little endian file support

### ISSUE THREAD

**Issue by ic-scm** [kenrick95/nikku#17]
The BRSTM reader module does not work with little endian files. The endianness of the file is specified in the byte order mark at offset 0x04 (https://wiibrew.org/wiki/BRSTM_file#BRSTM_header, 0xFEFF for big endian and 0xFFFE for little endian), but the BRSTM reader ignores that, and when a little endian file is loaded the reader still tries to interpret it as a big endian file which will usually cause some crazy javascript error.

Little endian BRSTM files are very rare so this could be simply fixed by checking the byte order mark and returning some error like "Little endian files are not supported." when the byte order mark is little endian, but to support little endian files the reading functions like getSliceAsNumber would have to be changed to support both LE and BE numbers. This could probably be done by having two different functions (for example getSliceAsNumber_BE and getSliceAsNumber_LE) and then setting getSliceAsNumber as a pointer/reference to one of those functions (if javascript supports that) after reading the byte order mark from the file.

BCSTM/BFSTM files are often little endian, this issue would have to be fixed to implement a BCSTM/BFSTM reader in this module (issue #9).

**Comment by kenrick95** [comment]
Hmmm do you have a sample file for this? I'll try to look into it 🤔

**Comment by ic-scm** [comment]
Attaching a sample file. This is a custom made file (it didn't come from a game), but some other BRSTM readers can read it without issues.
[le-1.zip](https://github.com/kenrick95/nikku/files/5268460/le-1.zip)
