### ISSUE TITLE
Audio player cannot merge more than 2 tracks

### ISSUE THREAD

**Issue by ic-scm** [kenrick95/nikku#19]
The track/stream merger in the player doesn't seem to be able to merge more than 2 tracks at a time. When I enable more than 2 tracks, another track will go silent, and with some combinations it's even weirder and plays only 1 track or doesn't mix them properly. Tried with a 14 channel (7 stereo tracks) file, and an 8 channel file (4 stereo tracks), in both Chromium and Firefox based web browsers. I'm attaching a test 8 channel file with a different pair of sine waves on each track.
[8ch-sinetest.zip](https://github.com/kenrick95/nikku/files/5268872/8ch-sinetest.zip)

**Comment by kenrick95** [comment]
Looks like issue with the audio player, let me investigate this deeper, might take some time

**Comment by ic-scm** [comment]
The mixing could probably also be done with some simple math in the javascript code of the player if that solution doesn't work out.

**Comment by kenrick95** [comment]
That is actually quite a good idea although we might do a lot of calculations whenever the track selection changes. Let me consider this option too. Thanks

**Comment by ic-scm** [comment]
Take a look at this code if you need a reference: https://github.com/ic-scm/openrevolution/blob/master/src/rt_player/main.cpp#L156-L171
This is C++ code so obviously it runs much faster than javascript, but something similar would probably work fine in javascript too.

**Comment by ic-scm** [comment]
Still seems broken for me in chromium 84...

**Comment by kenrick95** [comment]
Oops wrong logic. Should be fixed now
