### ISSUE TITLE
Making an APK Version for Android

### ISSUE THREAD

**Issue by SpideyfanX** [kenrick95/nikku#28]
Greetings! I would like to inquire about if it would be possible to eventually create like an APK version of this BRSTM Player, in order to allow for us to play BRSTMs offline and on the go. Thanks!

**Comment by kenrick95** [comment]
It is possible to add support for offline mode running from browser but it would need a tremendous willpower and effort to make it as Android mobile application. So, no, it's not in my interest to do this. Thanks for understanding
