### ISSUE TITLE
Issue with the volume

### ISSUE THREAD

**Issue by Epicguy19** [kenrick95/nikku#33]
I love this player so much I have a dedicated bookmark for it whenever I want to listen to some music from my favorite games! There’s just one issue though. At the time of me making this comment, over the past few hours, I’ve been having an issue regarding the volume. Whenever I try to adjust it to turn the volume down, the audio just shuts off and the track bar completely bugs out, going off of the lane it’s supposed to be in and over to the sides of the page. It’s really bizarre, and this hasn’t happened before until now. It also only happens when I click on anything regarding the volume. The track bar itself is just fine, it’s just that the audio settings are really wonky as is. A proper fix as soon as you can would be more than helpful. Thanks!

**Comment by kenrick95** [comment]
Hi @Epicguy19, thanks for using it, but I couldn't seem to reproduce your issue.

Would you help to share more context that may be causing the issue? This can be: OS information & version, screen dimension, browser information & version, and the BRSTM file if possible too

Thank you

**Comment by Epicguy19** [comment]
Hi! Thank you for your reply. It turns out that the issue, as random and
annoying as it was, seems to have been temporary, since my BRSTM’s are
working fine now. Initially, this had affected all of my BRSTM’s, but
they’re all working as intended now. I’m not sure what brought this about,
but I’m glad that it’s resolved now, however it was.
